name: GitHub Actions Build
run-name: Building for ${{ github.sha }}
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          architecture: 'x64'

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Build Executable
        run: uv run python -m nuitka --standalone --windows-console-mode=force --output-dir=build/main.dist/ --include-data-dir=config=config main.py

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: build/main.dist/
          include-hidden-files: true