name: GitHub Actions Build
run-name: Building for ${{ github.sha }}
on:
  release:
    types: [ released ]
jobs:
  build:
    env:
      UV_INDEX: https://pypi.org/simple
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Build Executable
        run: uv run python -m nuitka --standalone --windows-console-mode=force --assume-yes-for-downloads --user-package-configuration-file=nuitka-package.config.yml --remove-output --lto=yes --output-dir=build -o MaaXuexi main.py

      - name: Copy Resource Linux Macos
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
        run: |
          cp -r resource build/main.dist/resource
          cp -r config build/main.dist/config

      - name: Copy Resource Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          xcopy .\resource\ build\main.dist\resource\ /S /I
          xcopy .\config\ build\main.dist\config\ /S /I

      - name: Compress Build
        run: 7z a -t7z -mx=9 -mmt -ms -r MaaXuexi-${{ matrix.os }}-${{ github.sha }}.7z "./build/main.dist/*"

      - name: Upload Artifacts To Cloudflare
        uses: magicwallet/r2-upload@main
        with:
          endpoint: ${{ secrets.R2_ENDPOINT }}
          access_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.R2_ACCESS_SECRET_KEY }}
          bucket: maaxuexi
          file: ./MaaXuexi-${{ matrix.os }}-${{ github.sha }}.7z
