name: GitHub Actions Build
run-name: Building for ${{ github.ref_name }}
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  vite-build:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.Store-Cache-Key.outputs.cache-key }}
    defaults:
      run:
        working-directory: ./front
    steps:
      - name: Check-out repository
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10
          run_install: false
          package_json_file: 'front/package.json'

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
          cache-dependency-path: 'front/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Frontend
        run: pnpm run build

      - name: Store Cache Key
        id: Store-Cache-Key
        run: echo "cache-key=frontpage-dist-${{ hashFiles('page/**') }}" >> "$GITHUB_OUTPUT"

      - name: Cache
        uses: actions/cache@v5.0.3
        with:
          path: page
          key: ${{ steps.Store-Cache-Key.outputs.cache-key }}

  build:
    env:
      UV_INDEX: https://pypi.org/simple
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    needs: vite-build

    steps:
      - name: Check-out repository
        uses: actions/checkout@v6

      - name: Restore cached frontend artifacts
        uses: actions/cache@v5.0.3
        with:
          path: page
          key: ${{ needs.vite-build.outputs.cache-key }}
          enableCrossOsArchive: true
          fail-on-cache-miss: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7.5.0
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version-file: "pyproject.toml"

      - name: Install Dependencies
        run: uv sync --dev

      - name: Setup Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: 'updater/go.mod'
          cache-dependency-path: "updater/go.sum"

      - name: Build Executable
        run: uv run python -m nuitka --standalone --windows-console-mode=force --assume-yes-for-downloads --user-package-configuration-file=nuitka-package.config.yml --remove-output --lto=yes --output-dir=build -o MaaXuexi webui.py

      - name: Copy Resource Linux Macos
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
        run: |
          cp -r resource build/webui.dist/resource
          cp -r config build/webui.dist/config
          cp -r page build/webui.dist/page

      - name: Copy Resource Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          del build\webui.dist\maa\bin\DirectML.dll
          xcopy .\resource\ build\webui.dist\resource\ /S /I
          xcopy .\config\ build\webui.dist\config\ /S /I
          xcopy .\page\ build\webui.dist\page\ /S /I

      - name: Create Version file
        run: echo "${{ github.ref_name }}" >> build/webui.dist/version

      - name: Determine OS Name
        uses: rishabhgupta/split-by@v1.0.1
        id: split
        with:
          string: ${{ matrix.os }}
          split-by: '-'

      - name: Build Updater Windows
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: ./updater
        run: go build -ldflags "-s -w" -o ../build/webui.dist/Updater.exe

      - name: Build Updater Linux Macos
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
        working-directory: ./updater
        run: go build -ldflags "-s -w" -o ../build/webui.dist/Updater

      - name: Compress Build
        run: 7z a -t7z -mx=9 -myx=9 -mmt -ms=e -mqs=on -mf=BCJ2 -r MaaXuexi-${{ steps.split.outputs._0 }}-${{ github.ref_name }}.7z "./build/webui.dist/*"

      - name: Release
        uses: ncipollo/release-action@v1.20.0
        with:
          draft: true
          allowUpdates: true
          artifacts: |
            MaaXuexi-${{ steps.split.outputs._0 }}-${{ github.ref_name }}.7z
